export const PAGES = {
  index: '/pages/index/index',
  album: '/pages/album/index',
  refine: '/pages/refine/index',
  create: '/pages/create/index',
  user: '/pages/user/index',
  album: '/pages/album/postNode',
  discover: '/pages/discover/index',
  message: '/pages/message/index',
  activity: '/pages/activity/Activity',
  setting: '/pages/setting/index',
  search: '/pages/search/index',
  faceswap: '/pages/faceswap/index',
  photo: '/pages/photo/index',
  userAgreements: '/pages/user/agreements/index',
  userPrivacy: '/pages/user/privacy/index',
};
